spring:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 0
    pool:
      max-active: 300 #\u6700\u5927\u8FDE\u63A5\u6570
      max-idle: 100 #\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5\u6570
      max-wait: -1 #\u6700\u5927\u7B49\u5F85\u65F6\u95F4
      min-idle: 0 #\u521D\u59CB\u5316\u8FDE\u63A5\u6570
  http:
    multipart:
      enabled: true # 默认支持文件上传
      file-size-threshold: 4KB #支持文件写入磁盘
      location:  D:/tomcat8.0.39-18080-老人平谷/webapps/data/tmp # 上传文件的临时目录
      max-file-size: 5Mb # 最大支持文件大小
      max-request-size: 50Mb # 最大支持请求大小

#  session:
#        store-type: redis



server:
  port: 8081
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
    accesslog:
      debug: true #请求响应数据调试
  use-forward-headers: true

security:
  jwt:
    secret: k09BQnaF
    expiration: 3600 #1小时过期时间

upload:
  #Disk upload
  work-folder-name: D:/tomcat8.0.39-18080-老人平谷/webapps/data/files #文件存储路径
  access-url: http://127.0.0.1:8090 #文件访问地址，可使用反向代理