package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.EvaluationTables;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface EvaluationTablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_TABLES
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_TABLES
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    int insert(EvaluationTables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_TABLES
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    EvaluationTables selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_TABLES
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    List<EvaluationTables> selectAll(String sqlParam);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_TABLES
     *
     * @mbggenerated Thu Jun 15 17:55:19 GMT+08:00 2017
     */
    int updateByPrimaryKey(EvaluationTables record);

    EvaluationTables selectByTableName(String TABLE_NAME);

    List<EvaluationTables> like(String tableinfo);

    List<Map<String,Object>>  getData(String tablename);

}