package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.EvaluationOrganization;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface EvaluationOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_ORGANIZATION
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_ORGANIZATION
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    int insert(EvaluationOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_ORGANIZATION
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    EvaluationOrganization selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_ORGANIZATION
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    List<EvaluationOrganization> selectAll();
    List<EvaluationOrganization> selectDepertment();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_ORGANIZATION
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    int updateByPrimaryKey(EvaluationOrganization record);
    List<EvaluationOrganization> selectByDepertment(EvaluationOrganization record);
}