package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.EvaluationOldmaninfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface EvaluationOldmaninfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_OLDMANINFO
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_OLDMANINFO
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    int insert(EvaluationOldmaninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_OLDMANINFO
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    EvaluationOldmaninfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_OLDMANINFO
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    List<EvaluationOldmaninfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_OLDMANINFO
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    int updateByPrimaryKey(EvaluationOldmaninfo record);
}