package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.Evaluation;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface EvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    int insert(Evaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    Evaluation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    List<Evaluation> selectAll(String param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    int updateByPrimaryKey(Evaluation record);
}