package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.EvaluationReport;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface EvaluationReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_REPORT
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_REPORT
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    int insert(EvaluationReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_REPORT
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    EvaluationReport selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_REPORT
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    List<EvaluationReport> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_REPORT
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    int updateByPrimaryKey(EvaluationReport record);
}