package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.EvaluationPerson;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface EvaluationPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_PERSON
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_PERSON
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    int insert(EvaluationPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_PERSON
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    EvaluationPerson selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_PERSON
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    List<EvaluationPerson> selectAll();
    List<EvaluationPerson> selectName();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_PERSON
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    int updateByPrimaryKey(EvaluationPerson record);
    List<EvaluationPerson> selectByName(EvaluationPerson record);
}