package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.EvaluationRecent;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface EvaluationRecentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_RECENT
     *
     * @mbggenerated Sat May 20 15:38:59 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_RECENT
     *
     * @mbggenerated Sat May 20 15:38:59 CST 2017
     */
    int insert(EvaluationRecent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_RECENT
     *
     * @mbggenerated Sat May 20 15:38:59 CST 2017
     */
    EvaluationRecent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_RECENT
     *
     * @mbggenerated Sat May 20 15:38:59 CST 2017
     */
    List<EvaluationRecent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATION_RECENT
     *
     * @mbggenerated Sat May 20 15:38:59 CST 2017
     */
    int updateByPrimaryKey(EvaluationRecent record);
}