package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.ImDevelopAccount;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ImDevelopAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_DEVELOP_ACCOUNT
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_DEVELOP_ACCOUNT
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    int insert(ImDevelopAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_DEVELOP_ACCOUNT
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    ImDevelopAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_DEVELOP_ACCOUNT
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    List<ImDevelopAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IM_DEVELOP_ACCOUNT
     *
     * @mbggenerated Fri Jul 28 09:06:03 GMT+08:00 2017
     */
    int updateByPrimaryKey(ImDevelopAccount record);

    ImDevelopAccount selectInUse();

}