package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.JobB;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface JobBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_B
     *
     * @mbggenerated Tue Jun 20 12:49:26 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_B
     *
     * @mbggenerated Tue Jun 20 12:49:26 CST 2017
     */
    int insert(JobB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_B
     *
     * @mbggenerated Tue Jun 20 12:49:26 CST 2017
     */
    JobB selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_B
     *
     * @mbggenerated Tue Jun 20 12:49:26 CST 2017
     */
    List<JobB> selectAll(String param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_B
     *
     * @mbggenerated Tue Jun 20 12:49:26 CST 2017
     */
    int updateByPrimaryKey(JobB record);

    JobB getJobByNameGroupid(String jobname, String groupid);
}