package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.PensionOldmaninfoB;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PensionOldmaninfoBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PENSION_OLDMANINFO_B
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PENSION_OLDMANINFO_B
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    int insert(PensionOldmaninfoB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PENSION_OLDMANINFO_B
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    PensionOldmaninfoB selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PENSION_OLDMANINFO_B
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    List<PensionOldmaninfoB> selectAll(String param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PENSION_OLDMANINFO_B
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    int updateByPrimaryKey(PensionOldmaninfoB record);

    List<PensionOldmaninfoB> selectOldManInfoList(String param);

}