package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SmsBookB;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SmsBookBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_BOOK_B
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_BOOK_B
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    int insert(SmsBookB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_BOOK_B
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    SmsBookB selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_BOOK_B
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    List<SmsBookB> selectAll(String param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_BOOK_B
     *
     * @mbggenerated Thu Jul 27 16:40:10 CST 2017
     */
    int updateByPrimaryKey(SmsBookB record);
}