package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SmsManB;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SmsManBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_MAN_B
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_MAN_B
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    int insert(SmsManB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_MAN_B
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    SmsManB selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_MAN_B
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    List<SmsManB> selectAll(String param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_MAN_B
     *
     * @mbggenerated Thu Jul 27 16:40:22 CST 2017
     */
    int updateByPrimaryKey(SmsManB record);
}