package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SmsRecordB;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SmsRecordBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_RECORD_B
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_RECORD_B
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    int insert(SmsRecordB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_RECORD_B
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    SmsRecordB selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_RECORD_B
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    List<SmsRecordB> selectAll(String param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_RECORD_B
     *
     * @mbggenerated Thu Jul 27 16:39:42 CST 2017
     */
    int updateByPrimaryKey(SmsRecordB record);
}