package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SmsWarnB;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SmsWarnBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_WARN_B
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_WARN_B
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    int insert(SmsWarnB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_WARN_B
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    SmsWarnB selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_WARN_B
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    List<SmsWarnB> selectAll(String param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SMS_WARN_B
     *
     * @mbggenerated Tue Aug 01 10:43:57 CST 2017
     */
    int updateByPrimaryKey(SmsWarnB record);
}
