package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SocialContacts;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SocialContactsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOCIAL_CONTACTS
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOCIAL_CONTACTS
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    int insert(SocialContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOCIAL_CONTACTS
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    SocialContacts selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOCIAL_CONTACTS
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    List<SocialContacts> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOCIAL_CONTACTS
     *
     * @mbggenerated Thu Jul 13 12:45:18 GMT+08:00 2017
     */
    int updateByPrimaryKey(SocialContacts record);

    SocialContacts selectByUserID(String systemUserId);


    int deleteBySubAccountSid(String subAccountSid);

    List<SocialContacts> likeByFriendlyName(String friendlyname);
}