package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SystemUploadnode;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface SystemUploadnodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_UPLOADNODE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    int insert(SystemUploadnode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_UPLOADNODE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    List<SystemUploadnode> selectAll(String param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_UPLOADNODE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    int updatePnodeType(SystemUploadnode systemUploadnode);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_UPLOADNODE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */

    int  updateNodeName(SystemUploadnode systemUploadnode);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_UPLOADNODE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    int deleteNodeById(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_UPLOADNODE
     *
     * @mbggenerated Tue Jul 11 10:39:23 CST 2017
     */
    SystemUploadnode selectNodeById(String id);

    List<SystemUploadnode> selectNodeByPid(String id);


   List<SystemUploadnode> selectNodeByName(String name,String parentId);

}