package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SystemTableProperty;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SystemTablePropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TABLE_PROPERTY
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TABLE_PROPERTY
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    int insert(SystemTableProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TABLE_PROPERTY
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    SystemTableProperty selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TABLE_PROPERTY
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    List<SystemTableProperty> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_TABLE_PROPERTY
     *
     * @mbggenerated Fri Jun 16 17:19:27 GMT+08:00 2017
     */
    int updateByPrimaryKey(SystemTableProperty record);

    List<SystemTableProperty> selectByTablename(String tablename);

    List<SystemTableProperty> selectByTableid(String tableid);

    int deleteByTableid(String tableid);

    int disableById(String id);

    List<SystemTableProperty> selectDisabled(String tableId);

    List<SystemTableProperty> selectToShow(String tableId);


}