package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SystemEditor;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface SystemEditorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_EDITOR
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    int deleteByPrimaryKey(SystemEditor systemEditor);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_EDITOR
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    int insert(SystemEditor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_EDITOR
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    SystemEditor selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_EDITOR
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    List<SystemEditor> selectAll(String param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_EDITOR
     *
     * @mbggenerated Mon Jun 26 13:52:49 CST 2017
     */
    int updateByPrimaryKey(SystemEditor record);
}