package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SystemMachine;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SystemMachineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MACHINE
     *
     * @mbggenerated Fri Jul 07 14:04:27 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MACHINE
     *
     * @mbggenerated Fri Jul 07 14:04:27 CST 2017
     */
    int insert(SystemMachine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MACHINE
     *
     * @mbggenerated Fri Jul 07 14:04:27 CST 2017
     */
    SystemMachine selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MACHINE
     *
     * @mbggenerated Fri Jul 07 14:04:27 CST 2017
     */
    List<SystemMachine> selectAll(String param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MACHINE
     *
     * @mbggenerated Fri Jul 07 14:04:27 CST 2017
     */
    int updateByPrimaryKey(SystemMachine record);

    SystemMachine isExistsByNO(String mno);
}