package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SystemNodefile;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface SystemNodefileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NODEFILE
     *
     * @mbggenerated Wed Jul 19 17:10:12 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NODEFILE
     *
     * @mbggenerated Wed Jul 19 17:10:12 CST 2017
     */
    int insert(SystemNodefile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NODEFILE
     *
     * @mbggenerated Wed Jul 19 17:10:12 CST 2017
     */
    List<SystemNodefile> selectByPrimaryKey(Long id);

    List<SystemNodefile> selectByPKandType(String param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NODEFILE
     *
     * @mbggenerated Wed Jul 19 17:10:12 CST 2017
     */
    List<SystemNodefile> selectAll(String param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_NODEFILE
     *
     * @mbggenerated Wed Jul 19 17:10:12 CST 2017
     */
    int updateByPrimaryKey(SystemNodefile record);
}