package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SystemMenu;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface SystemMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU
     *
     * @mbggenerated Mon Apr 24 15:44:57 CST 2017
     */
    int insert(SystemMenu record);

    List<SystemMenu> getIdsByRoleId(String roleId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_MENU
     *
     * @mbggenerated Mon Apr 24 15:44:57 CST 2017
     */
    List<SystemMenu> selectAll();


    List<SystemMenu> findListByUserId(String id);

    List<SystemMenu> findParamByUserId(String id,String permission,String type);

    List<SystemMenu> findAllParam(String id,String permission,String type);

    List<SystemMenu> findAllList();


    void update(SystemMenu systemMenu);

    void deleteById(String id);

    SystemMenu getByIdPermission(SystemMenu systemMenu);
}