package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SystemRoleMenu;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface SystemRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_ROLE_MENU
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    int insert(SystemRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_ROLE_MENU
     *
     * @mbggenerated Mon Apr 24 16:28:14 CST 2017
     */
    List<SystemRoleMenu> selectAll(String param);

    void deleteByRoleId(String roleId);

    void deleteByMenuId(String menuId);
}