package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SystemIp;
import com.zkzy.zyportal.system.api.viewModel.SimilarMap;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface SystemIpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_IP
     *
     * @mbggenerated Fri Jul 07 09:58:52 CST 2017
     */
    int deleteByPrimaryKey(String ip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_IP
     *
     * @mbggenerated Fri Jul 07 09:58:52 CST 2017
     */
    int insert(SystemIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_IP
     *
     * @mbggenerated Fri Jul 07 09:58:52 CST 2017
     */
    SystemIp selectByPrimaryKey(String ip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_IP
     *
     * @mbggenerated Fri Jul 07 09:58:52 CST 2017
     */
    List<SystemIp> selectAll(SystemIp systemIp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_IP
     *
     * @mbggenerated Fri Jul 07 09:58:52 CST 2017
     */
    int updateByPrimaryKey(SystemIp record);

    int updateTime(SystemIp record);

    int updateStatus(SystemIp systemIp);

    List<SystemIp> queryAllnoWhere();
}