package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.SystemLog;
import com.zkzy.zyportal.system.api.viewModel.LogCount;
import com.zkzy.zyportal.system.api.viewModel.LogPolyline;
import com.zkzy.zyportal.system.api.viewModel.LogTop;
import com.zkzy.zyportal.system.api.viewModel.UserLoginLog;
import org.apache.ibatis.annotations.Mapper;


import java.util.List;

@Mapper
public interface SystemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOG
     *
     * @mbggenerated Mon Jul 10 13:19:14 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOG
     *
     * @mbggenerated Mon Jul 10 13:19:14 CST 2017
     */
    int insert(SystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOG
     *
     * @mbggenerated Mon Jul 10 13:19:14 CST 2017
     */
    SystemLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOG
     *
     * @mbggenerated Mon Jul 10 13:19:14 CST 2017
     */
    List<SystemLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_LOG
     *
     * @mbggenerated Mon Jul 10 13:19:14 CST 2017
     */
    int updateByPrimaryKey(SystemLog record);

    List<LogPolyline> queryLogGroupByDate(LogPolyline logPolyline);

    List<LogPolyline> queryAllLogGroupByPermission();

    List<UserLoginLog> queryUserLoginLog(UserLoginLog userLoginLog);

    List<LogCount> queryLogCount(String param);
    String selectPermissionCount(String param);
    List<LogCount> selectPermissionCountDateGroup(String param);
	List<LogTop> queryMenuTop(String sql);
    int queryMenuTopOther(String sql);


}