package com.zkzy.zyportal.system.provider.mapper;

import com.zkzy.zyportal.system.api.entity.WxNews;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface WxNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_NEWS
     *
     * @mbggenerated Tue Aug 22 13:40:05 GMT+08:00 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_NEWS
     *
     * @mbggenerated Tue Aug 22 13:40:05 GMT+08:00 2017
     */
    int insert(WxNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_NEWS
     *
     * @mbggenerated Tue Aug 22 13:40:05 GMT+08:00 2017
     */
    WxNews selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_NEWS
     *
     * @mbggenerated Tue Aug 22 13:40:05 GMT+08:00 2017
     */
    List<WxNews> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WX_NEWS
     *
     * @mbggenerated Tue Aug 22 13:40:05 GMT+08:00 2017
     */
    int updateByPrimaryKey(WxNews record);
}