package com.zkzy.zyportal.system.api.entity.grain;

import java.io.Serializable;
import java.math.BigDecimal;

public class GrainProjectsprogress implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.ID
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.ENTERPRISENAME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String enterprisename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.PROJECTNAME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String projectname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.PROJECTNUMBER
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private BigDecimal projectnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.PLANSTARTTIME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String planstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.PLANENDTIME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String planendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.SCALEANDCONTENT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String scaleandcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.WAREHOUSECOUNT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double warehousecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.STORAGEROOMCOUNT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double storageroomcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.TOTALPROJECTINVESTMENT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double totalprojectinvestment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.CENTRALPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double centralpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.AREAPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double areapay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.LOANPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double loanpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.FOREIGNPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double foreignpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.OTHERPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double otherpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.INPLACEPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double inplacepay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.INPLACECENTRALPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double inplacecentralpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.INPLACEAREAPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double inplaceareapay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.INPLACELOANPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double inplaceloanpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.INPLACEFOREIGNPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double inplaceforeignpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.INPLACEOTHERPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double inplaceotherpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.ALREADYSTARTEDNUMBER
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private BigDecimal alreadystartednumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.APPROVEDPROJECTNUMBER
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private BigDecimal approvedprojectnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.UNDERWAYPROJECTNUMBER
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private BigDecimal underwayprojectnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.ACCUMULATIVETOTALINVESTMENT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double accumulativetotalinvestment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.INVESTMENTCOMPLETED
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private Double investmentcompleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.PROJECTCAPACITY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String projectcapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.ISSUES
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String issues;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.REMARKS
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.REPORTINGTIME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String reportingtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.REPORTINGUNIT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String reportingunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.COUNTTIME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String counttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.REPORTPEOPLE
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String reportpeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRAIN_PROJECTSPROGRESS.TEL
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.ID
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.ID
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.ID
     *
     * @param id the value for GRAIN_PROJECTSPROGRESS.ID
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.ENTERPRISENAME
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.ENTERPRISENAME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getEnterprisename() {
        return enterprisename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.ENTERPRISENAME
     *
     * @param enterprisename the value for GRAIN_PROJECTSPROGRESS.ENTERPRISENAME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setEnterprisename(String enterprisename) {
        this.enterprisename = enterprisename == null ? null : enterprisename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.PROJECTNAME
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.PROJECTNAME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.PROJECTNAME
     *
     * @param projectname the value for GRAIN_PROJECTSPROGRESS.PROJECTNAME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname == null ? null : projectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.PROJECTNUMBER
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.PROJECTNUMBER
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public BigDecimal getProjectnumber() {
        return projectnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.PROJECTNUMBER
     *
     * @param projectnumber the value for GRAIN_PROJECTSPROGRESS.PROJECTNUMBER
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setProjectnumber(BigDecimal projectnumber) {
        this.projectnumber = projectnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.PLANSTARTTIME
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.PLANSTARTTIME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getPlanstarttime() {
        return planstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.PLANSTARTTIME
     *
     * @param planstarttime the value for GRAIN_PROJECTSPROGRESS.PLANSTARTTIME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setPlanstarttime(String planstarttime) {
        this.planstarttime = planstarttime == null ? null : planstarttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.PLANENDTIME
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.PLANENDTIME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getPlanendtime() {
        return planendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.PLANENDTIME
     *
     * @param planendtime the value for GRAIN_PROJECTSPROGRESS.PLANENDTIME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setPlanendtime(String planendtime) {
        this.planendtime = planendtime == null ? null : planendtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.SCALEANDCONTENT
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.SCALEANDCONTENT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getScaleandcontent() {
        return scaleandcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.SCALEANDCONTENT
     *
     * @param scaleandcontent the value for GRAIN_PROJECTSPROGRESS.SCALEANDCONTENT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setScaleandcontent(String scaleandcontent) {
        this.scaleandcontent = scaleandcontent == null ? null : scaleandcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.WAREHOUSECOUNT
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.WAREHOUSECOUNT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getWarehousecount() {
        return warehousecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.WAREHOUSECOUNT
     *
     * @param warehousecount the value for GRAIN_PROJECTSPROGRESS.WAREHOUSECOUNT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setWarehousecount(Double warehousecount) {
        this.warehousecount = warehousecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.STORAGEROOMCOUNT
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.STORAGEROOMCOUNT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getStorageroomcount() {
        return storageroomcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.STORAGEROOMCOUNT
     *
     * @param storageroomcount the value for GRAIN_PROJECTSPROGRESS.STORAGEROOMCOUNT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setStorageroomcount(Double storageroomcount) {
        this.storageroomcount = storageroomcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.TOTALPROJECTINVESTMENT
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.TOTALPROJECTINVESTMENT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getTotalprojectinvestment() {
        return totalprojectinvestment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.TOTALPROJECTINVESTMENT
     *
     * @param totalprojectinvestment the value for GRAIN_PROJECTSPROGRESS.TOTALPROJECTINVESTMENT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setTotalprojectinvestment(Double totalprojectinvestment) {
        this.totalprojectinvestment = totalprojectinvestment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.CENTRALPAY
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.CENTRALPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getCentralpay() {
        return centralpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.CENTRALPAY
     *
     * @param centralpay the value for GRAIN_PROJECTSPROGRESS.CENTRALPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setCentralpay(Double centralpay) {
        this.centralpay = centralpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.AREAPAY
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.AREAPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getAreapay() {
        return areapay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.AREAPAY
     *
     * @param areapay the value for GRAIN_PROJECTSPROGRESS.AREAPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setAreapay(Double areapay) {
        this.areapay = areapay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.LOANPAY
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.LOANPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getLoanpay() {
        return loanpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.LOANPAY
     *
     * @param loanpay the value for GRAIN_PROJECTSPROGRESS.LOANPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setLoanpay(Double loanpay) {
        this.loanpay = loanpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.FOREIGNPAY
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.FOREIGNPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getForeignpay() {
        return foreignpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.FOREIGNPAY
     *
     * @param foreignpay the value for GRAIN_PROJECTSPROGRESS.FOREIGNPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setForeignpay(Double foreignpay) {
        this.foreignpay = foreignpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.OTHERPAY
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.OTHERPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getOtherpay() {
        return otherpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.OTHERPAY
     *
     * @param otherpay the value for GRAIN_PROJECTSPROGRESS.OTHERPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setOtherpay(Double otherpay) {
        this.otherpay = otherpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.INPLACEPAY
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.INPLACEPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getInplacepay() {
        return inplacepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.INPLACEPAY
     *
     * @param inplacepay the value for GRAIN_PROJECTSPROGRESS.INPLACEPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setInplacepay(Double inplacepay) {
        this.inplacepay = inplacepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.INPLACECENTRALPAY
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.INPLACECENTRALPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getInplacecentralpay() {
        return inplacecentralpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.INPLACECENTRALPAY
     *
     * @param inplacecentralpay the value for GRAIN_PROJECTSPROGRESS.INPLACECENTRALPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setInplacecentralpay(Double inplacecentralpay) {
        this.inplacecentralpay = inplacecentralpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.INPLACEAREAPAY
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.INPLACEAREAPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getInplaceareapay() {
        return inplaceareapay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.INPLACEAREAPAY
     *
     * @param inplaceareapay the value for GRAIN_PROJECTSPROGRESS.INPLACEAREAPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setInplaceareapay(Double inplaceareapay) {
        this.inplaceareapay = inplaceareapay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.INPLACELOANPAY
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.INPLACELOANPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getInplaceloanpay() {
        return inplaceloanpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.INPLACELOANPAY
     *
     * @param inplaceloanpay the value for GRAIN_PROJECTSPROGRESS.INPLACELOANPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setInplaceloanpay(Double inplaceloanpay) {
        this.inplaceloanpay = inplaceloanpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.INPLACEFOREIGNPAY
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.INPLACEFOREIGNPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getInplaceforeignpay() {
        return inplaceforeignpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.INPLACEFOREIGNPAY
     *
     * @param inplaceforeignpay the value for GRAIN_PROJECTSPROGRESS.INPLACEFOREIGNPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setInplaceforeignpay(Double inplaceforeignpay) {
        this.inplaceforeignpay = inplaceforeignpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.INPLACEOTHERPAY
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.INPLACEOTHERPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getInplaceotherpay() {
        return inplaceotherpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.INPLACEOTHERPAY
     *
     * @param inplaceotherpay the value for GRAIN_PROJECTSPROGRESS.INPLACEOTHERPAY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setInplaceotherpay(Double inplaceotherpay) {
        this.inplaceotherpay = inplaceotherpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.ALREADYSTARTEDNUMBER
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.ALREADYSTARTEDNUMBER
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public BigDecimal getAlreadystartednumber() {
        return alreadystartednumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.ALREADYSTARTEDNUMBER
     *
     * @param alreadystartednumber the value for GRAIN_PROJECTSPROGRESS.ALREADYSTARTEDNUMBER
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setAlreadystartednumber(BigDecimal alreadystartednumber) {
        this.alreadystartednumber = alreadystartednumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.APPROVEDPROJECTNUMBER
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.APPROVEDPROJECTNUMBER
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public BigDecimal getApprovedprojectnumber() {
        return approvedprojectnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.APPROVEDPROJECTNUMBER
     *
     * @param approvedprojectnumber the value for GRAIN_PROJECTSPROGRESS.APPROVEDPROJECTNUMBER
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setApprovedprojectnumber(BigDecimal approvedprojectnumber) {
        this.approvedprojectnumber = approvedprojectnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.UNDERWAYPROJECTNUMBER
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.UNDERWAYPROJECTNUMBER
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public BigDecimal getUnderwayprojectnumber() {
        return underwayprojectnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.UNDERWAYPROJECTNUMBER
     *
     * @param underwayprojectnumber the value for GRAIN_PROJECTSPROGRESS.UNDERWAYPROJECTNUMBER
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setUnderwayprojectnumber(BigDecimal underwayprojectnumber) {
        this.underwayprojectnumber = underwayprojectnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.ACCUMULATIVETOTALINVESTMENT
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.ACCUMULATIVETOTALINVESTMENT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getAccumulativetotalinvestment() {
        return accumulativetotalinvestment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.ACCUMULATIVETOTALINVESTMENT
     *
     * @param accumulativetotalinvestment the value for GRAIN_PROJECTSPROGRESS.ACCUMULATIVETOTALINVESTMENT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setAccumulativetotalinvestment(Double accumulativetotalinvestment) {
        this.accumulativetotalinvestment = accumulativetotalinvestment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.INVESTMENTCOMPLETED
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.INVESTMENTCOMPLETED
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public Double getInvestmentcompleted() {
        return investmentcompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.INVESTMENTCOMPLETED
     *
     * @param investmentcompleted the value for GRAIN_PROJECTSPROGRESS.INVESTMENTCOMPLETED
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setInvestmentcompleted(Double investmentcompleted) {
        this.investmentcompleted = investmentcompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.PROJECTCAPACITY
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.PROJECTCAPACITY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getProjectcapacity() {
        return projectcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.PROJECTCAPACITY
     *
     * @param projectcapacity the value for GRAIN_PROJECTSPROGRESS.PROJECTCAPACITY
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setProjectcapacity(String projectcapacity) {
        this.projectcapacity = projectcapacity == null ? null : projectcapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.ISSUES
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.ISSUES
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getIssues() {
        return issues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.ISSUES
     *
     * @param issues the value for GRAIN_PROJECTSPROGRESS.ISSUES
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setIssues(String issues) {
        this.issues = issues == null ? null : issues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.REMARKS
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.REMARKS
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.REMARKS
     *
     * @param remarks the value for GRAIN_PROJECTSPROGRESS.REMARKS
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.REPORTINGTIME
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.REPORTINGTIME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getReportingtime() {
        return reportingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.REPORTINGTIME
     *
     * @param reportingtime the value for GRAIN_PROJECTSPROGRESS.REPORTINGTIME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setReportingtime(String reportingtime) {
        this.reportingtime = reportingtime == null ? null : reportingtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.REPORTINGUNIT
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.REPORTINGUNIT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getReportingunit() {
        return reportingunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.REPORTINGUNIT
     *
     * @param reportingunit the value for GRAIN_PROJECTSPROGRESS.REPORTINGUNIT
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setReportingunit(String reportingunit) {
        this.reportingunit = reportingunit == null ? null : reportingunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.COUNTTIME
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.COUNTTIME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getCounttime() {
        return counttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.COUNTTIME
     *
     * @param counttime the value for GRAIN_PROJECTSPROGRESS.COUNTTIME
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setCounttime(String counttime) {
        this.counttime = counttime == null ? null : counttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.REPORTPEOPLE
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.REPORTPEOPLE
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getReportpeople() {
        return reportpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.REPORTPEOPLE
     *
     * @param reportpeople the value for GRAIN_PROJECTSPROGRESS.REPORTPEOPLE
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setReportpeople(String reportpeople) {
        this.reportpeople = reportpeople == null ? null : reportpeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRAIN_PROJECTSPROGRESS.TEL
     *
     * @return the value of GRAIN_PROJECTSPROGRESS.TEL
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRAIN_PROJECTSPROGRESS.TEL
     *
     * @param tel the value for GRAIN_PROJECTSPROGRESS.TEL
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }
}