package com.zkzy.zyportal.system.api.entity;

import java.io.Serializable;

public class AreaAdministrationareaB implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREA_ADMINISTRATIONAREA_B.ID
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREA_ADMINISTRATIONAREA_B.PROVINCE
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREA_ADMINISTRATIONAREA_B.CREATETIME
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREA_ADMINISTRATIONAREA_B.MODIFYTIME
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    private String modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREA_ADMINISTRATIONAREA_B.CITY
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREA_ADMINISTRATIONAREA_B.AREA
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    private String area;


    private String Street;

    public String getStreet() {
        return Street;
    }

    public void setStreet(String street) {
        Street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREA_ADMINISTRATIONAREA_B.ID
     *
     * @return the value of AREA_ADMINISTRATIONAREA_B.ID
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREA_ADMINISTRATIONAREA_B.ID
     *
     * @param id the value for AREA_ADMINISTRATIONAREA_B.ID
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREA_ADMINISTRATIONAREA_B.PROVINCE
     *
     * @return the value of AREA_ADMINISTRATIONAREA_B.PROVINCE
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREA_ADMINISTRATIONAREA_B.PROVINCE
     *
     * @param province the value for AREA_ADMINISTRATIONAREA_B.PROVINCE
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREA_ADMINISTRATIONAREA_B.CREATETIME
     *
     * @return the value of AREA_ADMINISTRATIONAREA_B.CREATETIME
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREA_ADMINISTRATIONAREA_B.CREATETIME
     *
     * @param createtime the value for AREA_ADMINISTRATIONAREA_B.CREATETIME
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREA_ADMINISTRATIONAREA_B.MODIFYTIME
     *
     * @return the value of AREA_ADMINISTRATIONAREA_B.MODIFYTIME
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREA_ADMINISTRATIONAREA_B.MODIFYTIME
     *
     * @param modifytime the value for AREA_ADMINISTRATIONAREA_B.MODIFYTIME
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime == null ? null : modifytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREA_ADMINISTRATIONAREA_B.CITY
     *
     * @return the value of AREA_ADMINISTRATIONAREA_B.CITY
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREA_ADMINISTRATIONAREA_B.CITY
     *
     * @param city the value for AREA_ADMINISTRATIONAREA_B.CITY
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREA_ADMINISTRATIONAREA_B.AREA
     *
     * @return the value of AREA_ADMINISTRATIONAREA_B.AREA
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREA_ADMINISTRATIONAREA_B.AREA
     *
     * @param area the value for AREA_ADMINISTRATIONAREA_B.AREA
     *
     * @mbggenerated Wed May 10 14:33:53 CST 2017
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

}