package com.zkzy.zyportal.system.api.entity;

import java.io.Serializable;

public class EvaluationReport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.ID
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.NO
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.DATE_REPORT
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String dateReport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.CAUSE
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String cause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.NAME
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.GENDER
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.DATE_BIRTH
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String dateBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.AGENCY
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String agency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.ASSESSOR
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String assessor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.LEVEL1RATING
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String level1rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.PRELIMINARY_LEVEL
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String preliminaryLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.GRADE_CHANGE_CLAUSE
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String gradeChangeClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.FINAL_GRADE
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String finalGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_REPORT.NURSING_GRADE
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    private String nursingGrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.ID
     *
     * @return the value of EVALUATION_REPORT.ID
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.ID
     *
     * @param id the value for EVALUATION_REPORT.ID
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.NO
     *
     * @return the value of EVALUATION_REPORT.NO
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.NO
     *
     * @param no the value for EVALUATION_REPORT.NO
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.DATE_REPORT
     *
     * @return the value of EVALUATION_REPORT.DATE_REPORT
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getDateReport() {
        return dateReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.DATE_REPORT
     *
     * @param dateReport the value for EVALUATION_REPORT.DATE_REPORT
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setDateReport(String dateReport) {
        this.dateReport = dateReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.CAUSE
     *
     * @return the value of EVALUATION_REPORT.CAUSE
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getCause() {
        return cause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.CAUSE
     *
     * @param cause the value for EVALUATION_REPORT.CAUSE
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setCause(String cause) {
        this.cause = cause == null ? null : cause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.NAME
     *
     * @return the value of EVALUATION_REPORT.NAME
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.NAME
     *
     * @param name the value for EVALUATION_REPORT.NAME
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.GENDER
     *
     * @return the value of EVALUATION_REPORT.GENDER
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.GENDER
     *
     * @param gender the value for EVALUATION_REPORT.GENDER
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.DATE_BIRTH
     *
     * @return the value of EVALUATION_REPORT.DATE_BIRTH
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getDateBirth() {
        return dateBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.DATE_BIRTH
     *
     * @param dateBirth the value for EVALUATION_REPORT.DATE_BIRTH
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setDateBirth(String dateBirth) {
        this.dateBirth = dateBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.AGENCY
     *
     * @return the value of EVALUATION_REPORT.AGENCY
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getAgency() {
        return agency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.AGENCY
     *
     * @param agency the value for EVALUATION_REPORT.AGENCY
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setAgency(String agency) {
        this.agency = agency == null ? null : agency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.ASSESSOR
     *
     * @return the value of EVALUATION_REPORT.ASSESSOR
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getAssessor() {
        return assessor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.ASSESSOR
     *
     * @param assessor the value for EVALUATION_REPORT.ASSESSOR
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setAssessor(String assessor) {
        this.assessor = assessor == null ? null : assessor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.LEVEL1RATING
     *
     * @return the value of EVALUATION_REPORT.LEVEL1RATING
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getLevel1rating() {
        return level1rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.LEVEL1RATING
     *
     * @param level1rating the value for EVALUATION_REPORT.LEVEL1RATING
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setLevel1rating(String level1rating) {
        this.level1rating = level1rating == null ? null : level1rating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.PRELIMINARY_LEVEL
     *
     * @return the value of EVALUATION_REPORT.PRELIMINARY_LEVEL
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getPreliminaryLevel() {
        return preliminaryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.PRELIMINARY_LEVEL
     *
     * @param preliminaryLevel the value for EVALUATION_REPORT.PRELIMINARY_LEVEL
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setPreliminaryLevel(String preliminaryLevel) {
        this.preliminaryLevel = preliminaryLevel == null ? null : preliminaryLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.GRADE_CHANGE_CLAUSE
     *
     * @return the value of EVALUATION_REPORT.GRADE_CHANGE_CLAUSE
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getGradeChangeClause() {
        return gradeChangeClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.GRADE_CHANGE_CLAUSE
     *
     * @param gradeChangeClause the value for EVALUATION_REPORT.GRADE_CHANGE_CLAUSE
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setGradeChangeClause(String gradeChangeClause) {
        this.gradeChangeClause = gradeChangeClause == null ? null : gradeChangeClause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.FINAL_GRADE
     *
     * @return the value of EVALUATION_REPORT.FINAL_GRADE
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getFinalGrade() {
        return finalGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.FINAL_GRADE
     *
     * @param finalGrade the value for EVALUATION_REPORT.FINAL_GRADE
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setFinalGrade(String finalGrade) {
        this.finalGrade = finalGrade == null ? null : finalGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_REPORT.NURSING_GRADE
     *
     * @return the value of EVALUATION_REPORT.NURSING_GRADE
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public String getNursingGrade() {
        return nursingGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_REPORT.NURSING_GRADE
     *
     * @param nursingGrade the value for EVALUATION_REPORT.NURSING_GRADE
     *
     * @mbggenerated Wed May 17 13:24:53 CST 2017
     */
    public void setNursingGrade(String nursingGrade) {
        this.nursingGrade = nursingGrade == null ? null : nursingGrade.trim();
    }
}