package com.zkzy.zyportal.system.api.entity;

import java.io.Serializable;

public class EvaluationOldmaninfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.ID
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.NAME
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.SEX
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.HASRELIGION
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String hasreligion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.RELIGION
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String religion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.PCARDID
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String pcardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.CULTURE
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String culture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.REGISTERADDRESS
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String registeraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.RESIDENTADDRESS
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String residentaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.LIVINGSTATUS
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String livingstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.ECONOMICSFROM
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String economicsfrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.MEDICALPAYTYPE
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String medicalpaytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.MARITALSTATUS
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String maritalstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.BIRTH
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.SOCIALCARDID
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String socialcardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.FAMOUSFAMILY
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String famousfamily;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.CONTACTPERSON
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String contactperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.CONTACTTEL
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String contacttel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.PHOTOURL
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String photourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.RECENTRATING
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String recentrating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.CREATETIME
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.MODIFYTIME
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_OLDMANINFO.NURSINGHOMEID
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    private String nursinghomeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.ID
     *
     * @return the value of EVALUATION_OLDMANINFO.ID
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.ID
     *
     * @param id the value for EVALUATION_OLDMANINFO.ID
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.NAME
     *
     * @return the value of EVALUATION_OLDMANINFO.NAME
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.NAME
     *
     * @param name the value for EVALUATION_OLDMANINFO.NAME
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.SEX
     *
     * @return the value of EVALUATION_OLDMANINFO.SEX
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.SEX
     *
     * @param sex the value for EVALUATION_OLDMANINFO.SEX
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.HASRELIGION
     *
     * @return the value of EVALUATION_OLDMANINFO.HASRELIGION
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getHasreligion() {
        return hasreligion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.HASRELIGION
     *
     * @param hasreligion the value for EVALUATION_OLDMANINFO.HASRELIGION
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setHasreligion(String hasreligion) {
        this.hasreligion = hasreligion == null ? null : hasreligion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.RELIGION
     *
     * @return the value of EVALUATION_OLDMANINFO.RELIGION
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getReligion() {
        return religion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.RELIGION
     *
     * @param religion the value for EVALUATION_OLDMANINFO.RELIGION
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setReligion(String religion) {
        this.religion = religion == null ? null : religion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.PCARDID
     *
     * @return the value of EVALUATION_OLDMANINFO.PCARDID
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getPcardid() {
        return pcardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.PCARDID
     *
     * @param pcardid the value for EVALUATION_OLDMANINFO.PCARDID
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setPcardid(String pcardid) {
        this.pcardid = pcardid == null ? null : pcardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.CULTURE
     *
     * @return the value of EVALUATION_OLDMANINFO.CULTURE
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getCulture() {
        return culture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.CULTURE
     *
     * @param culture the value for EVALUATION_OLDMANINFO.CULTURE
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setCulture(String culture) {
        this.culture = culture == null ? null : culture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.REGISTERADDRESS
     *
     * @return the value of EVALUATION_OLDMANINFO.REGISTERADDRESS
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getRegisteraddress() {
        return registeraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.REGISTERADDRESS
     *
     * @param registeraddress the value for EVALUATION_OLDMANINFO.REGISTERADDRESS
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setRegisteraddress(String registeraddress) {
        this.registeraddress = registeraddress == null ? null : registeraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.RESIDENTADDRESS
     *
     * @return the value of EVALUATION_OLDMANINFO.RESIDENTADDRESS
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getResidentaddress() {
        return residentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.RESIDENTADDRESS
     *
     * @param residentaddress the value for EVALUATION_OLDMANINFO.RESIDENTADDRESS
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setResidentaddress(String residentaddress) {
        this.residentaddress = residentaddress == null ? null : residentaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.LIVINGSTATUS
     *
     * @return the value of EVALUATION_OLDMANINFO.LIVINGSTATUS
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getLivingstatus() {
        return livingstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.LIVINGSTATUS
     *
     * @param livingstatus the value for EVALUATION_OLDMANINFO.LIVINGSTATUS
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setLivingstatus(String livingstatus) {
        this.livingstatus = livingstatus == null ? null : livingstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.ECONOMICSFROM
     *
     * @return the value of EVALUATION_OLDMANINFO.ECONOMICSFROM
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getEconomicsfrom() {
        return economicsfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.ECONOMICSFROM
     *
     * @param economicsfrom the value for EVALUATION_OLDMANINFO.ECONOMICSFROM
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setEconomicsfrom(String economicsfrom) {
        this.economicsfrom = economicsfrom == null ? null : economicsfrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.MEDICALPAYTYPE
     *
     * @return the value of EVALUATION_OLDMANINFO.MEDICALPAYTYPE
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getMedicalpaytype() {
        return medicalpaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.MEDICALPAYTYPE
     *
     * @param medicalpaytype the value for EVALUATION_OLDMANINFO.MEDICALPAYTYPE
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setMedicalpaytype(String medicalpaytype) {
        this.medicalpaytype = medicalpaytype == null ? null : medicalpaytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.MARITALSTATUS
     *
     * @return the value of EVALUATION_OLDMANINFO.MARITALSTATUS
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getMaritalstatus() {
        return maritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.MARITALSTATUS
     *
     * @param maritalstatus the value for EVALUATION_OLDMANINFO.MARITALSTATUS
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setMaritalstatus(String maritalstatus) {
        this.maritalstatus = maritalstatus == null ? null : maritalstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.BIRTH
     *
     * @return the value of EVALUATION_OLDMANINFO.BIRTH
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.BIRTH
     *
     * @param birth the value for EVALUATION_OLDMANINFO.BIRTH
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.SOCIALCARDID
     *
     * @return the value of EVALUATION_OLDMANINFO.SOCIALCARDID
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getSocialcardid() {
        return socialcardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.SOCIALCARDID
     *
     * @param socialcardid the value for EVALUATION_OLDMANINFO.SOCIALCARDID
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setSocialcardid(String socialcardid) {
        this.socialcardid = socialcardid == null ? null : socialcardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.FAMOUSFAMILY
     *
     * @return the value of EVALUATION_OLDMANINFO.FAMOUSFAMILY
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getFamousfamily() {
        return famousfamily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.FAMOUSFAMILY
     *
     * @param famousfamily the value for EVALUATION_OLDMANINFO.FAMOUSFAMILY
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setFamousfamily(String famousfamily) {
        this.famousfamily = famousfamily == null ? null : famousfamily.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.CONTACTPERSON
     *
     * @return the value of EVALUATION_OLDMANINFO.CONTACTPERSON
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getContactperson() {
        return contactperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.CONTACTPERSON
     *
     * @param contactperson the value for EVALUATION_OLDMANINFO.CONTACTPERSON
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setContactperson(String contactperson) {
        this.contactperson = contactperson == null ? null : contactperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.CONTACTTEL
     *
     * @return the value of EVALUATION_OLDMANINFO.CONTACTTEL
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getContacttel() {
        return contacttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.CONTACTTEL
     *
     * @param contacttel the value for EVALUATION_OLDMANINFO.CONTACTTEL
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setContacttel(String contacttel) {
        this.contacttel = contacttel == null ? null : contacttel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.PHOTOURL
     *
     * @return the value of EVALUATION_OLDMANINFO.PHOTOURL
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getPhotourl() {
        return photourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.PHOTOURL
     *
     * @param photourl the value for EVALUATION_OLDMANINFO.PHOTOURL
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setPhotourl(String photourl) {
        this.photourl = photourl == null ? null : photourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.RECENTRATING
     *
     * @return the value of EVALUATION_OLDMANINFO.RECENTRATING
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getRecentrating() {
        return recentrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.RECENTRATING
     *
     * @param recentrating the value for EVALUATION_OLDMANINFO.RECENTRATING
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setRecentrating(String recentrating) {
        this.recentrating = recentrating == null ? null : recentrating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.CREATETIME
     *
     * @return the value of EVALUATION_OLDMANINFO.CREATETIME
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.CREATETIME
     *
     * @param createtime the value for EVALUATION_OLDMANINFO.CREATETIME
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.MODIFYTIME
     *
     * @return the value of EVALUATION_OLDMANINFO.MODIFYTIME
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.MODIFYTIME
     *
     * @param modifytime the value for EVALUATION_OLDMANINFO.MODIFYTIME
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime == null ? null : modifytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_OLDMANINFO.NURSINGHOMEID
     *
     * @return the value of EVALUATION_OLDMANINFO.NURSINGHOMEID
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public String getNursinghomeid() {
        return nursinghomeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_OLDMANINFO.NURSINGHOMEID
     *
     * @param nursinghomeid the value for EVALUATION_OLDMANINFO.NURSINGHOMEID
     *
     * @mbggenerated Wed May 24 13:05:48 CST 2017
     */
    public void setNursinghomeid(String nursinghomeid) {
        this.nursinghomeid = nursinghomeid == null ? null : nursinghomeid.trim();
    }
}