package com.zkzy.zyportal.system.api.entity;
import java.io.Serializable;
public class EvaluationOrganization implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_ORGANIZATION.ID
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_ORGANIZATION.STAFFCOUNT
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String staffcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_ORGANIZATION.CREATETIME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_ORGANIZATION.MODIFYTIME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_ORGANIZATION.ADDRESS
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_ORGANIZATION.LINKMAN
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_ORGANIZATION.PHONE
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_ORGANIZATION.DEPARTMENT
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_ORGANIZATION.ID
     *
     * @return the value of EVALUATION_ORGANIZATION.ID
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_ORGANIZATION.ID
     *
     * @param id the value for EVALUATION_ORGANIZATION.ID
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_ORGANIZATION.STAFFCOUNT
     *
     * @return the value of EVALUATION_ORGANIZATION.STAFFCOUNT
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getStaffcount() {
        return staffcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_ORGANIZATION.STAFFCOUNT
     *
     * @param staffcount the value for EVALUATION_ORGANIZATION.STAFFCOUNT
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setStaffcount(String staffcount) {
        this.staffcount = staffcount == null ? null : staffcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_ORGANIZATION.CREATETIME
     *
     * @return the value of EVALUATION_ORGANIZATION.CREATETIME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_ORGANIZATION.CREATETIME
     *
     * @param createtime the value for EVALUATION_ORGANIZATION.CREATETIME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_ORGANIZATION.MODIFYTIME
     *
     * @return the value of EVALUATION_ORGANIZATION.MODIFYTIME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_ORGANIZATION.MODIFYTIME
     *
     * @param modifytime the value for EVALUATION_ORGANIZATION.MODIFYTIME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime == null ? null : modifytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_ORGANIZATION.ADDRESS
     *
     * @return the value of EVALUATION_ORGANIZATION.ADDRESS
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_ORGANIZATION.ADDRESS
     *
     * @param address the value for EVALUATION_ORGANIZATION.ADDRESS
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_ORGANIZATION.LINKMAN
     *
     * @return the value of EVALUATION_ORGANIZATION.LINKMAN
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_ORGANIZATION.LINKMAN
     *
     * @param linkman the value for EVALUATION_ORGANIZATION.LINKMAN
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_ORGANIZATION.PHONE
     *
     * @return the value of EVALUATION_ORGANIZATION.PHONE
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_ORGANIZATION.PHONE
     *
     * @param phone the value for EVALUATION_ORGANIZATION.PHONE
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_ORGANIZATION.DEPARTMENT
     *
     * @return the value of EVALUATION_ORGANIZATION.DEPARTMENT
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_ORGANIZATION.DEPARTMENT
     *
     * @param department the value for EVALUATION_ORGANIZATION.DEPARTMENT
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }
}