package com.zkzy.zyportal.system.api.entity;
import java.io.Serializable;
public class EvaluationPerson implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_PERSON.ID
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_PERSON.NAME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_PERSON.PHONE
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_PERSON.ORGANIZATION
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_PERSON.CREATETIME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVALUATION_PERSON.MODIFYTIME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    private String modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_PERSON.ID
     *
     * @return the value of EVALUATION_PERSON.ID
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_PERSON.ID
     *
     * @param id the value for EVALUATION_PERSON.ID
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_PERSON.NAME
     *
     * @return the value of EVALUATION_PERSON.NAME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_PERSON.NAME
     *
     * @param name the value for EVALUATION_PERSON.NAME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_PERSON.PHONE
     *
     * @return the value of EVALUATION_PERSON.PHONE
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_PERSON.PHONE
     *
     * @param phone the value for EVALUATION_PERSON.PHONE
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_PERSON.ORGANIZATION
     *
     * @return the value of EVALUATION_PERSON.ORGANIZATION
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_PERSON.ORGANIZATION
     *
     * @param organization the value for EVALUATION_PERSON.ORGANIZATION
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_PERSON.CREATETIME
     *
     * @return the value of EVALUATION_PERSON.CREATETIME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_PERSON.CREATETIME
     *
     * @param createtime the value for EVALUATION_PERSON.CREATETIME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVALUATION_PERSON.MODIFYTIME
     *
     * @return the value of EVALUATION_PERSON.MODIFYTIME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVALUATION_PERSON.MODIFYTIME
     *
     * @param modifytime the value for EVALUATION_PERSON.MODIFYTIME
     *
     * @mbggenerated Fri May 12 13:49:32 CST 2017
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime == null ? null : modifytime.trim();
    }
}