package com.zkzy.zyportal.system.api.entity;

import java.io.Serializable;

public class PensionOldmanhomeB implements Serializable  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PENSION_OLDMANHOME_B.ID
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PENSION_OLDMANHOME_B.NAME
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PENSION_OLDMANHOME_B.PHONE
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PENSION_OLDMANHOME_B.
ADDRESS
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    private String 
address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PENSION_OLDMANHOME_B.CREATETIME
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PENSION_OLDMANHOME_B.MODIFYTIME
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    private String modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PENSION_OLDMANHOME_B.AREA
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    private String area;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PENSION_OLDMANHOME_B.ID
     *
     * @return the value of PENSION_OLDMANHOME_B.ID
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PENSION_OLDMANHOME_B.ID
     *
     * @param id the value for PENSION_OLDMANHOME_B.ID
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PENSION_OLDMANHOME_B.NAME
     *
     * @return the value of PENSION_OLDMANHOME_B.NAME
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PENSION_OLDMANHOME_B.NAME
     *
     * @param name the value for PENSION_OLDMANHOME_B.NAME
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PENSION_OLDMANHOME_B.PHONE
     *
     * @return the value of PENSION_OLDMANHOME_B.PHONE
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PENSION_OLDMANHOME_B.PHONE
     *
     * @param phone the value for PENSION_OLDMANHOME_B.PHONE
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PENSION_OLDMANHOME_B.
ADDRESS
     *
     * @return the value of PENSION_OLDMANHOME_B.
ADDRESS
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public String getaddress() {
        return 
address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PENSION_OLDMANHOME_B.
ADDRESS
     *
     * @param 
address the value for PENSION_OLDMANHOME_B.
ADDRESS
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public void setaddress(String
address) {
        this.
address = 
address == null ? null : 
address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PENSION_OLDMANHOME_B.CREATETIME
     *
     * @return the value of PENSION_OLDMANHOME_B.CREATETIME
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PENSION_OLDMANHOME_B.CREATETIME
     *
     * @param createtime the value for PENSION_OLDMANHOME_B.CREATETIME
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PENSION_OLDMANHOME_B.MODIFYTIME
     *
     * @return the value of PENSION_OLDMANHOME_B.MODIFYTIME
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PENSION_OLDMANHOME_B.MODIFYTIME
     *
     * @param modifytime the value for PENSION_OLDMANHOME_B.MODIFYTIME
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime == null ? null : modifytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PENSION_OLDMANHOME_B.AREA
     *
     * @return the value of PENSION_OLDMANHOME_B.AREA
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PENSION_OLDMANHOME_B.AREA
     *
     * @param area the value for PENSION_OLDMANHOME_B.AREA
     *
     * @mbggenerated Wed May 10 16:40:27 CST 2017
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }
}