package com.zkzy.zyportal.system.api.entity;

public class PensionOldmanhomerealR {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PENSION_OLDMANHOMEREAL_R.ID
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PENSION_OLDMANHOMEREAL_R.OLDMANID
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    private String oldmanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PENSION_OLDMANHOMEREAL_R.NURSINGHOMEID
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    private String nursinghomeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PENSION_OLDMANHOMEREAL_R.CREATETIME
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PENSION_OLDMANHOMEREAL_R.MODIFYTIME
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    private String modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PENSION_OLDMANHOMEREAL_R.ID
     *
     * @return the value of PENSION_OLDMANHOMEREAL_R.ID
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PENSION_OLDMANHOMEREAL_R.ID
     *
     * @param id the value for PENSION_OLDMANHOMEREAL_R.ID
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PENSION_OLDMANHOMEREAL_R.OLDMANID
     *
     * @return the value of PENSION_OLDMANHOMEREAL_R.OLDMANID
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    public String getOldmanid() {
        return oldmanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PENSION_OLDMANHOMEREAL_R.OLDMANID
     *
     * @param oldmanid the value for PENSION_OLDMANHOMEREAL_R.OLDMANID
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    public void setOldmanid(String oldmanid) {
        this.oldmanid = oldmanid == null ? null : oldmanid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PENSION_OLDMANHOMEREAL_R.NURSINGHOMEID
     *
     * @return the value of PENSION_OLDMANHOMEREAL_R.NURSINGHOMEID
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    public String getNursinghomeid() {
        return nursinghomeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PENSION_OLDMANHOMEREAL_R.NURSINGHOMEID
     *
     * @param nursinghomeid the value for PENSION_OLDMANHOMEREAL_R.NURSINGHOMEID
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    public void setNursinghomeid(String nursinghomeid) {
        this.nursinghomeid = nursinghomeid == null ? null : nursinghomeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PENSION_OLDMANHOMEREAL_R.CREATETIME
     *
     * @return the value of PENSION_OLDMANHOMEREAL_R.CREATETIME
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PENSION_OLDMANHOMEREAL_R.CREATETIME
     *
     * @param createtime the value for PENSION_OLDMANHOMEREAL_R.CREATETIME
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PENSION_OLDMANHOMEREAL_R.MODIFYTIME
     *
     * @return the value of PENSION_OLDMANHOMEREAL_R.MODIFYTIME
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PENSION_OLDMANHOMEREAL_R.MODIFYTIME
     *
     * @param modifytime the value for PENSION_OLDMANHOMEREAL_R.MODIFYTIME
     *
     * @mbggenerated Mon May 08 17:32:08 CST 2017
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime == null ? null : modifytime.trim();
    }
}