package com.zkzy.zyportal.system.provider.mapper.grain;

import com.zkzy.zyportal.system.api.entity.grain.GrainProjectsprogress;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface GrainProjectsprogressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GRAIN_PROJECTSPROGRESS
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GRAIN_PROJECTSPROGRESS
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    int insert(GrainProjectsprogress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GRAIN_PROJECTSPROGRESS
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    GrainProjectsprogress selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GRAIN_PROJECTSPROGRESS
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    List<GrainProjectsprogress> selectAll(String param);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GRAIN_PROJECTSPROGRESS
     *
     * @mbggenerated Tue Sep 12 17:09:25 CST 2017
     */
    int updateByPrimaryKey(GrainProjectsprogress record);
}